/* Aaroogyam CRM1 Advanced Business Layer - V3.1 */
(function(){'use strict';
const URL='https://ielebadardbzmoxantsc.supabase.co',KEY='sb_publishable_0pekrOT6vhYZYQ48wHr7Ag_NPcpobGj';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let db=null,me=null,profile=null;
const roles={super_admin:'Super Admin',management:'Management',order_manager:'Order Manager',agent:'Agent',dealer:'Dealer',warehouse:'Warehouse',courier_manager:'Courier Manager'};
const canManage=()=>['super_admin','management','order_manager'].includes(profile?.role),canUseLeads=()=>['super_admin','management','order_manager','agent'].includes(profile?.role);
function toast(msg){const t=$('toast');if(t){t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}else console.log(msg)}
function modal(title,html){const m=$('modal');if(!m)return;$('modalTitle').textContent=title;$('modalContent').innerHTML=html;m.style.display='grid'}
function closeModal(){$('modal')?.style.setProperty('display','none')}
function style(){if($('crmAdvancedLayerStyle'))return;const s=document.createElement('style');s.id='crmAdvancedLayerStyle';s.textContent='.crm-adv-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.crm-adv-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.crm-adv-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.crm-adv-form .wide{grid-column:1/-1}@media(max-width:900px){.crm-adv-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.crm-adv-grid,.crm-adv-form{grid-template-columns:1fr}}';document.head.appendChild(s)}
function section(id,title,sub,body){if($(id))return $(id);const e=document.createElement('section');e.id=id;e.className='page';e.innerHTML=`<div class="title"><div><h2>${title}</h2><div class="sub">${sub}</div></div></div>${body}`;document.querySelector('.main')?.appendChild(e);return e}
function pages(){section('crmCampaigns','Campaigns','Meta / Google / Website / manual campaign management',`<div class="panel"><div class="crm-adv-actions"><button class="btn" id="crmNewCampaign">+ New Campaign</button><button class="btn alt" id="crmRefreshCampaign">Refresh</button></div><div class="tablewrap"><table><thead><tr><th>Campaign</th><th>Source</th><th>Platform</th><th>Status</th><th>Daily Budget</th><th>Created</th></tr></thead><tbody id="crmCampaignBody"></tbody></table></div></div>`);section('crmLeadManager','Lead Management','Lead queue, assignment, follow-up and conversion',`<div class="panel"><div class="crm-adv-actions"><button class="btn" id="crmNewLead">+ New Lead</button><button class="btn alt" id="crmRefreshLead">Refresh</button></div><div class="tablewrap"><table><thead><tr><th>Lead</th><th>Mobile</th><th>Source</th><th>Status</th><th>Priority</th><th>Assigned</th><th>Follow-up</th><th>Action</th></tr></thead><tbody id="crmLeadBody"></tbody></table></div></div>`);section('crmCustomer360','Customer 360','Customer profile, orders and interaction history',`<div class="panel"><div class="search"><input id="crm360Mobile" placeholder="10 digit mobile"><button class="btn" id="crm360Search">Search</button></div></div><div id="crm360Result"></div>`)}
function addNav(){const nav=$('nav');if(!nav||nav.dataset.crmAdvancedV31)return;nav.dataset.crmAdvancedV31='1';const add=(id,label,ok)=>{if(!ok)return;const b=document.createElement('button');b.type='button';b.id='crmNav_'+id;b.textContent=label;b.onclick=()=>show(id);nav.appendChild(b)};add('crmCampaigns','📣 Campaigns',canManage());add('crmLeadManager','🧲 Lead Management',canUseLeads());add('crmCustomer360','👤 Customer 360',canUseLeads())}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));$('crmNav_'+id)?.classList.add('active');window.scrollTo(0,0);if(id==='crmCampaigns')loadCampaigns();if(id==='crmLeadManager')loadLeads()}
async function loadCampaigns(){const b=$('crmCampaignBody');if(!b||!db)return;b.innerHTML='<tr><td colspan="6" class="empty">Loading...</td></tr>';const {data,error}=await db.from('crm_campaigns').select('id,campaign_name,source,platform,status,daily_budget,created_at').order('created_at',{ascending:false}).limit(200);if(error){b.innerHTML=`<tr><td colspan="6" class="danger">${esc(error.message)}</td></tr>`;return}b.innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.campaign_name)}</td><td>${esc(x.source||'-')}</td><td>${esc(x.platform||'-')}</td><td><span class="pill">${esc(x.status||'-')}</span></td><td>₹${Number(x.daily_budget||0).toLocaleString('en-IN')}</td><td>${esc(new Date(x.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No campaigns</td></tr>'}
function campaignForm(){modal('New Campaign',`<div class="crm-adv-form"><div class="field wide"><label>Campaign Name *</label><input id="cName"></div><div class="field"><label>Source</label><select id="cSource"><option value="meta">Meta</option><option value="google">Google</option><option value="website">Website</option><option value="manual">Manual</option><option value="other">Other</option></select></div><div class="field"><label>Platform</label><input id="cPlatform" placeholder="Facebook / Instagram / Google Ads"></div><div class="field"><label>Status</label><select id="cStatus"><option value="active">Active</option><option value="draft">Draft</option><option value="paused">Paused</option><option value="closed">Closed</option></select></div><div class="field"><label>Daily Budget</label><input id="cBudget" type="number" min="0"></div><div class="field"><label>Total Budget</label><input id="cTotal" type="number" min="0"></div><div class="field wide"><label>Notes</label><textarea id="cNotes"></textarea></div></div><div class="actions"><button class="btn" id="cSave">Save Campaign</button></div>`);$('cSave').onclick=async()=>{const name=$('cName').value.trim();if(!name){toast('Campaign name required');return}const {error}=await db.from('crm_campaigns').insert({campaign_name:name,source:$('cSource').value,platform:$('cPlatform').value.trim()||null,status:$('cStatus').value,daily_budget:Number($('cBudget').value||0),total_budget:Number($('cTotal').value||0),notes:$('cNotes').value.trim()||null,created_by:me?.id||null});if(error){toast(error.message);return}closeModal();toast('Campaign created');loadCampaigns()}}
async function loadAgents(){const {data}=await db.from('profiles').select('id,full_name,role').eq('is_active',true).in('role',['agent','management','order_manager','super_admin']).order('full_name');return data||[]}
function leadForm(){modal('New Lead',`<div class="crm-adv-form"><div class="field"><label>Lead Name *</label><input id="lName"></div><div class="field"><label>Mobile *</label><input id="lMobile" inputmode="numeric" maxlength="10"></div><div class="field"><label>Source</label><select id="lSource"><option value="manual">Manual</option><option value="meta">Meta</option><option value="google">Google</option><option value="facebook">Facebook</option><option value="instagram">Instagram</option><option value="website">Website</option></select></div><div class="field"><label>Priority</label><select id="lPriority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></div><div class="field"><label>Status</label><select id="lStatus"><option value="new">New</option><option value="assigned">Assigned</option><option value="contacted">Contacted</option><option value="followup">Follow-up</option><option value="qualified">Qualified</option></select></div><div class="field"><label>Assign To</label><select id="lAgent"><option value="">Unassigned</option></select></div><div class="field wide"><label>Notes</label><textarea id="lNotes"></textarea></div></div><div class="actions"><button class="btn" id="lSave">Save Lead</button></div>`);loadAgents().then(a=>{$('lAgent').innerHTML='<option value="">Unassigned</option>'+a.map(x=>`<option value="${esc(x.id)}">${esc(x.full_name)} — ${esc(roles[x.role]||x.role)}</option>`).join('')});$('lSave').onclick=async()=>{const name=$('lName').value.trim(),mobile=$('lMobile').value.replace(/\D/g,'');if(!name||!/^[6-9]\d{9}$/.test(mobile)){toast('Valid name and 10 digit mobile required');return}const {error}=await db.from('crm_leads').insert({lead_name:name,mobile,source:$('lSource').value,priority:$('lPriority').value,lead_status:$('lStatus').value,assigned_to:$('lAgent').value||null,notes:$('lNotes').value.trim()||null,created_by:me?.id||null});if(error){toast(error.message);return}closeModal();toast('Lead created');loadLeads()}}
async function loadLeads(){const b=$('crmLeadBody');if(!b||!db)return;b.innerHTML='<tr><td colspan="8" class="empty">Loading...</td></tr>';let q=db.from('crm_leads').select('id,lead_name,mobile,source,lead_status,priority,next_followup_at,assigned_to,profiles:assigned_to(full_name)').order('created_at',{ascending:false}).limit(300);if(profile?.role==='agent')q=q.eq('assigned_to',me.id);const {data,error}=await q;if(error){b.innerHTML=`<tr><td colspan="8" class="danger">${esc(error.message)}</td></tr>`;return}b.innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.lead_name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.source||'-')}</td><td><span class="pill">${esc(x.lead_status||'-')}</span></td><td>${esc(x.priority||'-')}</td><td>${esc(x.profiles?.full_name||'-')}</td><td>${x.next_followup_at?esc(new Date(x.next_followup_at).toLocaleString()):'-'}</td><td><button class="btn alt crmLeadOpen" data-id="${esc(x.id)}">Open</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No leads</td></tr>';b.querySelectorAll('.crmLeadOpen').forEach(btn=>btn.onclick=()=>openLead(btn.dataset.id))}
async function logInteraction(payload){const {error}=await db.from('crm_interactions').insert({...payload,agent_id:me?.id||null,created_by:me?.id||null,started_at:new Date().toISOString()});if(error)toast(error.message);else toast('Interaction logged')}
async function openLead(id){const {data:l,error}=await db.from('crm_leads').select('*').eq('id',id).single();if(error){toast(error.message);return}modal('Lead: '+l.lead_name,`<div class="crm-adv-form"><div class="field"><label>Status</label><select id="oStatus"><option value="new">New</option><option value="assigned">Assigned</option><option value="contacted">Contacted</option><option value="followup">Follow-up</option><option value="qualified">Qualified</option><option value="converted">Converted</option><option value="lost">Lost</option></select></div><div class="field"><label>Priority</label><select id="oPriority"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><div class="field wide"><label>Next Follow-up</label><input id="oFollow" type="datetime-local"></div><div class="field wide"><label>Disposition / Note</label><textarea id="oNote"></textarea></div></div><div class="actions"><button class="btn alt" id="oCall">Log Outbound Call</button><button class="btn" id="oSave">Save</button></div>`);$('oStatus').value=l.lead_status||'new';$('oPriority').value=l.priority||'normal';if(l.next_followup_at)$('oFollow').value=new Date(l.next_followup_at).toISOString().slice(0,16);$('oCall').onclick=()=>logInteraction({lead_id:id,interaction_type:'call',direction:'outbound',status:$('oStatus').value});$('oSave').onclick=async()=>{const patch={lead_status:$('oStatus').value,priority:$('oPriority').value,next_followup_at:$('oFollow').value?new Date($('oFollow').value).toISOString():null,last_contact_at:new Date().toISOString()};const {error:e}=await db.from('crm_leads').update(patch).eq('id',id);if(e){toast(e.message);return}const note=$('oNote').value.trim();if(note)await logInteraction({lead_id:id,interaction_type:'note',direction:'internal',status:patch.lead_status,details:note});closeModal();toast('Lead updated');loadLeads()}}
async function customer360(){const m=$('crm360Mobile').value.replace(/\D/g,''),out=$('crm360Result');if(!/^[6-9]\d{9}$/.test(m)){out.innerHTML='<div class="panel">Valid 10 digit mobile enter करें.</div>';return}out.innerHTML='<div class="panel">Loading...</div>';const {data:c,error}=await db.from('customers').select('*').eq('mobile',m).maybeSingle();if(error||!c){out.innerHTML='<div class="panel empty">Customer not found.</div>';return}const [{data:orders},{data:leads},{data:ints}]=await Promise.all([db.from('orders').select('order_no,order_status,total_amount,order_date').eq('customer_id',c.id).order('order_date',{ascending:false}),db.from('crm_leads').select('lead_name,lead_status,priority,created_at').eq('customer_id',c.id).order('created_at',{ascending:false}),db.from('crm_interactions').select('interaction_type,direction,status,disposition,details,created_at').eq('customer_id',c.id).order('created_at',{ascending:false}).limit(100)]);const total=(orders||[]).reduce((s,x)=>s+Number(x.total_amount||0),0);out.innerHTML=`<div class="panel"><h3>${esc(c.customer_name)}</h3><div class="sub">${esc(c.mobile)} · ${esc(c.city||'')} · ${esc(c.state||'')}</div></div><div class="crm-adv-grid"><div class="stat"><span>Orders</span><b>${(orders||[]).length}</b></div><div class="stat"><span>Leads</span><b>${(leads||[]).length}</b></div><div class="stat"><span>Interactions</span><b>${(ints||[]).length}</b></div><div class="stat"><span>Lifetime Order Value</span><b>₹${total.toLocaleString('en-IN')}</b></div></div><div class="panel"><h3>Recent Orders</h3><div class="tablewrap"><table><thead><tr><th>Order</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>${(orders||[]).map(o=>`<tr><td>#${esc(o.order_no)}</td><td><span class="pill">${esc(o.order_status)}</span></td><td>₹${Number(o.total_amount||0).toLocaleString('en-IN')}</td><td>${esc(new Date(o.order_date).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No orders</td></tr>'}</tbody></table></div></div><div class="panel"><h3>Interaction History</h3><div class="tablewrap"><table><thead><tr><th>Type</th><th>Direction</th><th>Status</th><th>Details</th><th>Date</th></tr></thead><tbody>${(ints||[]).map(i=>`<tr><td>${esc(i.interaction_type)}</td><td>${esc(i.direction||'-')}</td><td>${esc(i.status||i.disposition||'-')}</td><td>${esc(i.details||'-')}</td><td>${esc(new Date(i.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No interactions</td></tr>'}</tbody></table></div></div>`}
function loadSupabaseScript(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient){resolve(window.supabase);return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>window.supabase?.createClient?resolve(window.supabase):reject(new Error('Supabase SDK global not available'));s.onerror=()=>reject(new Error('Supabase SDK failed to load'));document.head.appendChild(s)})}
async function init(){try{style();const sdk=await loadSupabaseScript();db=sdk.createClient(URL,KEY);const {data,error}=await db.auth.getUser();if(error||!data?.user)return;me=data.user;const r=await db.from('profiles').select('*').eq('id',me.id).maybeSingle();profile=r.data||null;if(!profile)return;pages();addNav();$('crmNewCampaign')?.addEventListener('click',campaignForm);$('crmRefreshCampaign')?.addEventListener('click',loadCampaigns);$('crmNewLead')?.addEventListener('click',leadForm);$('crmRefreshLead')?.addEventListener('click',loadLeads);$('crm360Search')?.addEventListener('click',customer360);$('crm360Mobile')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();customer360()}});if($('closeModal')&&!$('closeModal').dataset.advBound){$('closeModal').dataset.advBound='1';$('closeModal').addEventListener('click',closeModal)}}catch(e){console.error('CRM1 advanced layer init failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

/* Telephony UI loader: kept here so index.html does not need to be rewritten. */
(function(){
  function load(){
    if(window.__crm1TelephonyLoader)return;
    window.__crm1TelephonyLoader=true;
    if(document.querySelector('script[data-crm1-telephony]'))return;
    const s=document.createElement('script');
    s.src='./crm1-telephony-ui.js';
    s.async=true;
    s.dataset.crm1Telephony='1';
    document.head.appendChild(s);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
