import { test, expect } from '@playwright/test';
const credentials=()=>({email:process.env.CRM2_AGENT_EMAIL,password:process.env.CRM2_AGENT_PASSWORD});
async function login(page){const c=credentials();test.skip(!c.email||!c.password,'Missing agent secrets');await page.goto(process.env.CRM2_BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});await page.locator('#email').fill(c.email);await page.locator('#password').fill(c.password);await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page.getByRole('button',{name:'Logout',exact:true})).toBeVisible({timeout:10_000})}
async function openCreateOrder(page){await login(page);await page.getByRole('button',{name:'Orders',exact:true}).click();await page.getByRole('button',{name:/Create Order/i}).first().click();await expect(page.locator('[data-crm2-create-order]')).toBeVisible({timeout:8_000})}
test('agent: CRM1-style Create Order page has final section layout',async({page})=>{await openCreateOrder(page);await expect(page.getByRole('heading',{name:'Manual Phone Call Console',exact:false})).toBeVisible();await expect(page.getByRole('heading',{name:'Telephony',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Customer Details',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Order Details',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Remarks',exact:true})).toHaveCount(1);await expect(page.getByRole('heading',{name:'Disposition & Follow-up',exact:true})).toBeVisible();await expect(page.getByText('Disposition Level 1 *',{exact:true})).toBeVisible();await expect(page.getByText('Disposition Level 2 *',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Submit Disposition',exact:true})).toBeVisible();await expect(page.getByText('Order Summary',{exact:true})).toBeHidden();await expect(page.getByRole('button',{name:'Save & Follow-up',exact:true})).toBeHidden();await expect(page.getByRole('button',{name:'Fast Order',exact:true})).toHaveCount(0)});
test('agent: Manual Phone Call Console has CRM1 call controls and agent status options',async({page})=>{await openCreateOrder(page);await expect(page.getByLabel('Customer Mobile',{exact:true})).toBeVisible();const status=page.locator('#crm1ParityAgentStatus');await expect(status).toHaveValue(/ready/i);const start=page.getByRole('button',{name:'Start Call',exact:true});const end=page.getByRole('button',{name:'End Call',exact:true});await expect(start).toBeVisible();await expect(end).toBeVisible();await expect(start).toHaveCSS('background-color','rgb(22, 128, 60)');await expect(end).toHaveCSS('background-color','rgb(198, 40, 40)');await expect(page.locator('#crm2ParityCallTimer')).toHaveText('00:00');await expect(page.getByRole('button',{name:'Log Manual Call',exact:true})).toBeVisible();const options=page.locator('#crm1ParityAgentStatus option');await expect(options).toHaveText(['Ready','Pause','AUX','Washroom','Lunch','Meeting','Training','Break'])});
test('agent: Create Order product selector has requested ₹1999 products',async({page})=>{await openCreateOrder(page);const product=page.locator('#crm2OrderProduct');await expect(product).toContainText('Ortho Gold');await expect(product).toContainText('Nasha Naasham');await product.selectOption({label:'Ortho Gold'});await expect(page.locator('#crm2OrderPrice')).toHaveValue('1999');await product.selectOption({label:'Nasha Naasham'});await expect(page.locator('#crm2OrderPrice')).toHaveValue('1999')});
test('agent: Sales Order Level 2 contains Express, Urgent and Fresh Order',async({page})=>{await openCreateOrder(page);const l1=page.locator('#crm1Disposition1'),l2=page.locator('#crm1Disposition2');await l1.selectOption({label:'Sales Order'});await expect(l2).toBeEnabled();await expect(l2.locator('option')).toContainText(['Express Order','Urgent Order','Fresh Order'])});
test('agent: Create Order disposition Level 2 depends on Level 1',async({page})=>{await openCreateOrder(page);const l1=page.locator('#crm1Disposition1'),l2=page.locator('#crm1Disposition2');await expect(l1).toBeVisible();await expect(l2).toBeDisabled();await expect(l2).toHaveValue('');await l1.selectOption({label:'Lead Case'});await expect(l2).toBeEnabled();await expect(l2.locator('option')).toContainText(['Call Back','Dealer Enquiry','High Price','Just Enquiry','Online Enquiry','PNA'])});
test('agent: Create Order mirrors CRM1 validation rules and freezes discount at zero',async({page})=>{await openCreateOrder(page);const discount=page.locator('#crm2OrderDiscount');await expect(discount).toHaveValue('0');await expect(discount).toBeDisabled();await expect(page.locator('#crm2OrderPrice')).toHaveAttribute('readonly','');await expect(page.locator('#crm2OrderAge')).toHaveAttribute('maxlength','3');await expect(page.locator('#crm2OrderQty')).toHaveAttribute('min','1');await expect(page.locator('#crm2OrderQty')).toHaveAttribute('max','99');await expect(page.locator('#crm2OrderPincode')).toHaveAttribute('maxlength','6');await expect(page.locator('#crm2OrderMobile')).toHaveAttribute('maxlength','10');});
test('agent: Create Order rejects incomplete CRM1-required customer and order fields with English red errors',async({page})=>{await openCreateOrder(page);await page.locator('#crm2OrderMobile').fill('123');await page.locator('#crm2OrderName').fill('123');await page.locator('#crm2OrderPincode').fill('123');await page.locator('#crm2CreateOrder').evaluate((el)=>el.click());await expect(page.locator('#crm2OrderMobileError')).toContainText('10');await expect(page.locator('#crm2OrderNameError')).toContainText('name');await expect(page.locator('#crm2OrderPinError')).toContainText('6');for(const id of ['crm2OrderMobileError','crm2OrderNameError','crm2OrderPinError']){await expect(page.locator('#'+id)).toHaveCSS('color','rgb(211, 47, 47)');await expect(page.locator('#'+id)).not.toContainText(/कृपया|चयन करें|भरें|सही/)} });
test('agent: CRM2 login page contains no zero-cost or Hindi/demo validation copy',async({page})=>{await page.goto(process.env.CRM2_BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});const body=await page.locator('body').innerText();expect(body).not.toMatch(/zero cost/i);expect(body).not.toMatch(/कृपया|चयन करें|भरें|सही/);expect(body).not.toMatch(/demo/i)});
test('agent: Create Order remains responsive without horizontal overflow',async({page})=>{await openCreateOrder(page);for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);expect(overflow,`horizontal overflow at ${width}px`).toBe(false)}});
