import { test, expect } from '@playwright/test';
test.describe.configure({mode:'serial'});

const credentials=()=>({email:process.env.CRM2_AGENT_EMAIL,password:process.env.CRM2_AGENT_PASSWORD});
async function login(page){const c=credentials();test.skip(!c.email||!c.password,'Missing agent secrets');await page.goto(process.env.CRM2_BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});await page.locator('#email').fill(c.email);await page.locator('#password').fill(c.password);await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page.getByRole('button',{name:'Logout',exact:true})).toBeVisible({timeout:10_000})}
async function openCreateOrder(page){await login(page);await page.getByRole('button',{name:'Orders',exact:true}).click();await page.getByRole('button',{name:/Create Order/i}).first().click();await expect(page.locator('[data-crm2-create-order]')).toBeVisible({timeout:8_000});await expect(page.getByRole('heading',{name:'Manual Phone Call Console',exact:false})).toBeVisible()}
function uniqueMobile(){return '8'+String(Date.now()).slice(-9)}
async function latestCall(page,mobile){return page.evaluate(async(m)=>{const {sb}=await import('/crm2/data.js');const {data:leads,error:leadError}=await sb.from('leads').select('id').eq('mobile',m).order('created_at',{ascending:false}).limit(1);if(leadError||!leads?.[0])return {data:null,error:leadError};const {data,error}=await sb.from('lead_calls').select('id,lead_id,agent_id,started_at,ended_at,duration_seconds,outcome').eq('lead_id',leads[0].id).order('created_at',{ascending:false}).limit(1).maybeSingle();return {data,error}},mobile)}

test('agent: Start Call creates a real call and End Call persists duration',async({page})=>{await openCreateOrder(page);const mobile=uniqueMobile();await page.locator('#crm2OrderMobile').fill(mobile);await page.getByRole('button',{name:'Start Call',exact:true}).click();await expect(page.locator('#crm2CallStatus')).toContainText('Calling / In Call',{timeout:8_000});await expect(page.getByRole('button',{name:'Start Call',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'End Call',exact:true})).toBeEnabled();await page.waitForTimeout(2200);await expect(page.locator('#crm2CallTimer')).not.toHaveText('00:00');await page.getByRole('button',{name:'End Call',exact:true}).click();await expect(page.locator('#crm2CallStatus')).toHaveText('Call completed',{timeout:8_000});const result=await latestCall(page,mobile);expect(result.error).toBeNull();expect(result.data?.lead_id).toBeTruthy();expect(result.data?.started_at).toBeTruthy();expect(result.data?.ended_at).toBeTruthy();expect(Number(result.data?.duration_seconds)).toBeGreaterThan(0)});

test('agent: Log Manual Call creates a real DB call without a preloaded lead',async({page})=>{await openCreateOrder(page);const mobile=uniqueMobile();await page.locator('#crm2OrderMobile').fill(mobile);await page.getByRole('button',{name:'Log Manual Call',exact:true}).click();await expect(page.locator('#crm2CallStatus')).toHaveText('Manual call logged successfully',{timeout:8_000});const result=await latestCall(page,mobile);expect(result.error).toBeNull();expect(result.data?.lead_id).toBeTruthy();expect(result.data?.outcome).toBe('Manual Call Logged');expect(result.data?.ended_at).toBeTruthy()});

test('agent: Agent Status persists through CRM2 RPC and reload',async({page})=>{await openCreateOrder(page);const status=page.locator('#crm1ParityAgentStatus');await status.selectOption('pause');await expect.poll(async()=>page.evaluate(async()=>{const {sb}=await import('/crm2/data.js');const {data,error}=await sb.rpc('crm2_get_agent_status');return error?null:data?.status||null})).toBe('pause');await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Orders',exact:true}).click();await page.getByRole('button',{name:/Create Order/i}).first().click();await expect(page.locator('#crm1ParityAgentStatus')).toHaveValue('pause')});

test('agent: Submit non-sales disposition saves disposition and does not create an order',async({page})=>{await openCreateOrder(page);const mobile=uniqueMobile();await page.locator('#crm2OrderMobile').fill(mobile);await page.locator('#crm2OrderName').fill('CRM2 QA Non Sales');await page.locator('#crm1Disposition1').selectOption({label:'Lead Case'});await page.locator('#crm1Disposition2').selectOption({label:'High Price'});await page.locator('#crm2OrderRemarks').fill('Automated CRM2 functional QA');await page.getByRole('button',{name:'Submit Disposition',exact:true}).click();await expect(page.locator('#crm2OrderMessage')).toContainText('Disposition saved: High Price',{timeout:8_000});const result=await page.evaluate(async(m)=>{const {sb}=await import('/crm2/data.js');const {data:leads,error:leadError}=await sb.from('leads').select('id,disposition_id').eq('mobile',m).order('created_at',{ascending:false}).limit(1);if(leadError||!leads?.[0])return {leadError,order:null};const {data:orders,error:orderError}=await sb.from('orders').select('id').eq('lead_id',leads[0].id);return {leadError,orderError,lead:leads[0],order:orders||[]}},mobile);expect(result.leadError).toBeNull();expect(result.lead?.disposition_id).toBeTruthy();expect(result.orderError).toBeNull();expect(result.order).toHaveLength(0)});

test('agent: Sales Order Fresh creates a real order using master price',async({page})=>{await openCreateOrder(page);const mobile=uniqueMobile();await page.locator('#crm2OrderMobile').fill(mobile);await page.locator('#crm2OrderName').fill('CRM2 QA Sales Order');await page.locator('#crm2OrderPincode').fill('452001');await expect(page.locator('#crm2OrderState')).toBeEnabled({timeout:8_000});await page.locator('#crm2OrderState').selectOption({label:'Madhya Pradesh'});await expect(page.locator('#crm2OrderCity')).toBeEnabled({timeout:5_000});await page.locator('#crm2OrderCity').selectOption({label:'Indore'});await expect(page.locator('#crm2OrderPost')).toBeEnabled({timeout:5_000});const postValue=await page.locator('#crm2OrderPost option').nth(1).getAttribute('value');await page.locator('#crm2OrderPost').selectOption(postValue);await page.locator('#crm2OrderAddress').fill('CRM2 QA, 10 Test Street');await page.locator('#crm2OrderProduct').selectOption({label:'Ortho Gold'});await expect(page.locator('#crm2OrderPrice')).toHaveValue('1999');await page.locator('#crm1Disposition1').selectOption({label:'Sales Order'});await page.locator('#crm1Disposition2').selectOption({label:'Fresh Order'});await page.locator('#crm2OrderRemarks').fill('Automated CRM2 functional QA order');await page.getByRole('button',{name:'Submit Disposition',exact:true}).click();await expect(page.locator('#crm2OrderMessage')).toContainText('successfully',{timeout:12_000});const result=await page.evaluate(async(m)=>{const {sb}=await import('/crm2/data.js');const {data:customers,error:customerError}=await sb.from('customers').select('id').eq('mobile',m).limit(1);if(customerError||!customers?.[0])return {customerError,order:null,item:null};const {data:orders,error:orderError}=await sb.from('orders').select('id,order_code,total,discount,lead_id,customer_id').eq('customer_id',customers[0].id).order('created_at',{ascending:false}).limit(1);const order=orders?.[0];const {data:item,error:itemError}=order?await sb.from('order_items').select('product_name,unit_price,quantity,line_total').eq('order_id',order.id).limit(1):{data:null,error:null};return {customerError,orderError,itemError,order,item}},mobile);expect(result.customerError).toBeNull();expect(result.orderError).toBeNull();expect(result.itemError).toBeNull();expect(result.order?.order_code).toBeTruthy();expect(Number(result.order?.total)).toBe(1999);expect(Number(result.order?.discount)).toBe(0);expect(result.item?.[0]?.product_name).toBe('Ortho Gold');expect(Number(result.item?.[0]?.unit_price)).toBe(1999)});

test('agent: desktop call console keeps mobile, status and timer compact on one row',async({page})=>{await openCreateOrder(page);await page.setViewportSize({width:1366,height:900});const grid=page.locator('.crm1-parity-call-grid');await expect(grid).toBeVisible();const boxes=await grid.locator('.field').evaluateAll(nodes=>nodes.map(n=>Math.round(n.getBoundingClientRect().width)));expect(boxes.length).toBe(3);expect(boxes[1]).toBeLessThan(boxes[0]);expect(boxes[2]).toBeLessThan(boxes[0])});
