import {sb,esc,money,currentProfile} from '../data.js';
import {mountManagement} from './management-ui.js';
const ROLES=['super_admin','admin','manager','assistant_manager','team_leader'];
const roleList=['super_admin','admin','manager','assistant_manager','team_leader','agent','qa','verification','warehouse','dispatch','dealer_manager','accounts','mis','management_readonly'];
const RESTRICTED_PAGES={
 inventory:['super_admin','admin','manager','assistant_manager','team_leader','warehouse','dispatch'],
 dealers:['super_admin','admin','manager','assistant_manager','team_leader','dealer_manager'],
 delivery:['super_admin','admin','manager','assistant_manager','team_leader','warehouse','dispatch','dealer_manager','verification'],
 accounts:['super_admin','admin','manager','assistant_manager','accounts'],
 reports:['super_admin','admin','manager','assistant_manager','team_leader','qa','mis','management_readonly'],
 targets:['super_admin','admin','manager','assistant_manager','team_leader'],
 imports:['super_admin','admin','manager','assistant_manager','team_leader','mis'],
 audit:['super_admin','admin','manager','assistant_manager','qa','mis','management_readonly']
};
const CONFIGS={
 teams:{title:'Teams',table:'crm2_teams',fields:[['name','Name','text'],['manager_id','Manager ID','text'],['active','Active','check']]},
 dispositions:{title:'Dispositions',table:'disposition_levels',fields:[['level_no','Level','number'],['name','Name','text'],['parent_id','Parent ID','text'],['active','Active','check']]},
 campaigns:{title:'Campaigns',table:'campaigns',fields:[['name','Name','text'],['source_id','Source ID','text'],['tv_channel','TV Channel','text'],['program','Program','text'],['time_slot','Time Slot','text'],['ad_identifier','Ad Identifier','text'],['spend','Spend','number'],['active','Active','check']]},
 products:{title:'Products',table:'products',fields:[['sku','SKU','text'],['name','Name','text'],['cost','Cost','number'],['mrp','MRP','number'],['selling_price','Selling Price','number'],['active','Active','check']]},
 warehouses:{title:'Warehouses',table:'crm2_warehouses',fields:[['code','Code','text'],['name','Name','text'],['address','Address','text'],['state','State','text'],['city','City','text'],['active','Active','check']]},
 couriers:{title:'Couriers',table:'couriers',fields:[['name','Name','text'],['active','Active','check']]}
};
let me;
const $=id=>document.getElementById(id),msg=t=>{const x=$('adminMsg');if(x)x.textContent=t};
const table=(h,r)=>`<div class="tablewrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.length?r.join(''):`<tr><td colspan="${h.length}" class="muted">No records found.</td></tr>`}</tbody></table></div>`;
const field=(f)=>{const [k,l,t]=f;return `<div class="field"><label>${esc(l)}</label>${t==='check'?`<input id="af_${k}" type="checkbox" checked>`:`<input id="af_${k}" type="${t==='number'?'number':'text'}">`}`};
const activateNav=id=>document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));
export function applyRoleNavigation(profile=me){if(!profile)return;document.querySelectorAll('[data-page]').forEach(b=>{const allowed=RESTRICTED_PAGES[b.dataset.page];const hide=!!allowed&&!allowed.includes(profile.role);b.hidden=hide;b.style.display=hide?'none':''});const side=document.querySelector('.side');if(!side)return;['management_assignments','management_mis'].forEach(id=>{const old=side.querySelector(`[data-page="${id}"]`);if(old)old.remove()});if(ROLES.includes(profile.role)){for(const [id,label,mode] of [['management_assignments','Lead Assignment','assignments'],['management_mis','MIS Drilldown','mis']]){const b=document.createElement('button');b.dataset.page=id;b.textContent=label;b.onclick=()=>{activateNav(id);mountManagement(document.querySelector('#main'),mode)};side.appendChild(b)}}}
function addAdminNav(side,p){if(side.querySelector('[data-page="admin"]')||!ROLES.includes(p.role))return;const b=document.createElement('button');b.dataset.page='admin';b.textContent='Admin / Config';b.onclick=()=>{activateNav('admin');mountAdmin(document.querySelector('#main'))};side.appendChild(b)}
function home(m){m.innerHTML=`<div class="title"><h2>Admin & Configuration</h2></div><section class="panel"><p id="adminMsg" class="msg"></p><div class="cards"><button class="btn" data-admin="users">Users & Roles</button><button class="btn" data-admin="assignments">Lead Assignment</button><button class="btn" data-admin="mis">MIS Drilldown</button>${Object.entries(CONFIGS).map(([k,v])=>`<button class="btn" data-admin="${k}">${v.title}</button>`).join('')}</div></section>`;document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>{if(b.dataset.admin==='users')users(m);else if(b.dataset.admin==='assignments'){activateNav('management_assignments');assignments(m)}else if(b.dataset.admin==='mis'){activateNav('management_mis');mountManagement(m,'mis')}else configPage(m,b.dataset.admin)})}
async function configPage(m,key){const c=CONFIGS[key];const order=c.table==='disposition_levels'?'level_no':'created_at';const {data,error}=await sb.from(c.table).select('*').order(order,{ascending:true}).limit(300);const rows=(data||[]).map(r=>`<tr><td>${esc(String(r.id).slice(0,8))}</td>${c.fields.map(([f,,t])=>`<td>${t==='check'?(r[f]?'Yes':'No'):t==='number'?money(r[f]):esc(r[f]??'')}</td>`).join('')}<td><button class="btn alt" data-edit="${r.id}">Load</button></td></tr>`);m.innerHTML=`<div class="title"><h2>${esc(c.title)}</h2><button class="btn alt" id="aback">Admin Home</button></div><section class="panel"><form id="cfg" class="grid2">${c.fields.map(field).join('')}<button class="btn">Add</button><div id="adminMsg" class="msg"></div></form></section><section class="panel">${error?`<p class="error">${esc(error.message)}</p>`:table(['ID',...c.fields.map(x=>x[1]),'Action'],rows)}</section>`;$('aback').onclick=()=>home(m);$('cfg').onsubmit=async e=>{e.preventDefault();const p={};c.fields.forEach(([f,,t])=>p[f]=t==='check'?$(('af_'+f)).checked:t==='number'?Number($(('af_'+f)).value||0):$(('af_'+f)).value.trim()||null);const {error}=await sb.from(c.table).insert(p);if(error)msg(error.message);else configPage(m,key)};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const {data:r}=await sb.from(c.table).select('*').eq('id',b.dataset.edit).single();if(!r)return;c.fields.forEach(([f,,t])=>{const x=$('af_'+f);if(t==='check')x.checked=!!r[f];else x.value=r[f]??''});window.scrollTo({top:0,behavior:'smooth'});msg('Loaded existing values. Add creates a new configuration record.')})}
async function users(m){const [{data:p,error},{data:t}]=await Promise.all([sb.from('crm2_user_profiles').select('id,full_name,role,team_id,active').order('created_at',{ascending:false}).limit(300),sb.from('crm2_teams').select('id,name').eq('active',true).order('name')]);const rows=(p||[]).map(r=>`<tr><td>${esc(r.full_name||'')}</td><td>${esc(r.role)}</td><td>${esc((t||[]).find(x=>x.id===r.team_id)?.name||'')}</td><td>${r.active?'Active':'Inactive'}</td><td><button class="btn alt" data-user="${r.id}">Load</button></td></tr>`);m.innerHTML=`<div class="title"><h2>Users & Roles</h2><button class="btn alt" id="aback">Admin Home</button></div><section class="panel"><p class="muted">Manage existing CRM2 Auth-linked profiles. Creating Auth users still requires the protected Auth service and is not exposed in the browser.</p><form id="uf" class="grid2"><div class="field"><label>User ID</label><input id="uid" required></div><div class="field"><label>Full Name</label><input id="un"></div><div class="field"><label>Role</label><select id="ur">${roleList.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Team ID</label><input id="ut"></div><div class="field"><label>Active</label><input id="ua" type="checkbox" checked></div><button class="btn">Update Profile</button><div id="adminMsg" class="msg"></div></form></section><section class="panel">${error?`<p class="error">${esc(error.message)}</p>`:table(['Name','Role','Team','Status','Action'],rows)}</section>`;$('aback').onclick=()=>home(m);$('uf').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('crm2_user_profiles').update({full_name:$('un').value.trim()||null,role:$('ur').value,team_id:$('ut').value.trim()||null,active:$('ua').checked}).eq('id',$('uid').value.trim());if(error)msg(error.message);else{msg('Profile updated');users(m)}};document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{const {data:r}=await sb.from('crm2_user_profiles').select('id,full_name,role,team_id,active').eq('id',b.dataset.user).single();if(r){$('uid').value=r.id;$('un').value=r.full_name||'';$('ur').value=r.role;$('ut').value=r.team_id||'';$('ua').checked=!!r.active;window.scrollTo({top:0,behavior:'smooth'})}})}
async function assignments(m){const [{data:l,error},{data:a}]=await Promise.all([sb.from('leads').select('id,lead_code,customer_name,mobile,assigned_to').is('deleted_at',null).order('created_at',{ascending:false}).limit(200),sb.from('crm2_user_profiles').select('id,full_name').eq('active',true).in('role',['agent','team_leader']).order('full_name')]);const rows=(l||[]).map(x=>`<tr><td>${esc(x.lead_code)}</td><td>${esc(x.customer_name)}</td><td>${esc(x.mobile)}</td><td>${esc((a||[]).find(y=>y.id===x.assigned_to)?.full_name||'Unassigned')}</td><td><select data-assign="${x.id}"><option value="">Unassigned</option>${(a||[]).map(y=>`<option value="${y.id}" ${y.id===x.assigned_to?'selected':''}>${esc(y.full_name||y.id.slice(0,8))}</option>`).join('')}</select></td></tr>`);m.innerHTML=`<div class="title"><h2>Lead Assignment</h2><button class="btn alt" id="aback">Admin Home</button></div><section class="panel"><p id="adminMsg" class="msg"></p>${error?`<p class="error">${esc(error.message)}</p>`:table(['Lead','Customer','Mobile','Current Agent','Assign To'],rows)}</section>`;$('aback').onclick=()=>home(m);document.querySelectorAll('[data-assign]').forEach(s=>s.onchange=async()=>{const agent=s.value||null;const {data:profile}=agent?await sb.from('crm2_user_profiles').select('team_id').eq('id',agent).single():{data:null};const {error}=await sb.from('leads').update({assigned_to:agent,team_id:profile?.team_id||null,status:agent?'assigned':'new'}).eq('id',s.dataset.assign);if(error){msg(error.message);return}if(agent){const {error:e}=await sb.from('lead_assignments').insert({lead_id:s.dataset.assign,agent_id:agent,assigned_by:me.id,assignment_date:new Date().toISOString().slice(0,10),status:'active'});if(e)msg(e.message);else msg('Assignment updated and history recorded.')}else msg('Lead unassigned.')})}
export async function mountAdmin(m){me=await currentProfile();if(!me||!ROLES.includes(me.role)){m.innerHTML='<section class="panel error">Access denied.</section>';return}home(m);applyRoleNavigation(me)}
new MutationObserver(()=>{const side=document.querySelector('.side');if(!side||side.dataset.crm2NavReady==='1')return;side.dataset.crm2NavReady='1';if(me){applyRoleNavigation(me);addAdminNav(side,me);return}currentProfile().then(p=>{if(!p||!document.querySelector('.side'))return;me=p;applyRoleNavigation(p);addAdminNav(document.querySelector('.side'),p)})}).observe(document.body,{childList:true,subtree:true});