import {normalizeMobile} from '../data.js';
const REQUIRED=['customer_name','mobile'];
export function normalizeHeaders(headers){return headers.map(x=>String(x??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''))}
export function detectDuplicates(rows){const seenMobiles=new Set(),duplicateMobile=new Set();rows.forEach((r,i)=>{const m=normalizeMobile(r.mobile||'');if(m&&seenMobiles.has(m))duplicateMobile.add(i);if(m)seenMobiles.add(m)});return {seenMobiles,duplicateMobile}}
export function validateImportRows(rows){const errors=[],valid=[];const {duplicateMobile}=detectDuplicates(rows);rows.forEach((r,i)=>{const rowErrors=[];if(!String(r.customer_name||'').trim())rowErrors.push('Missing customer_name');if(!/^\d{10}$/.test(normalizeMobile(r.mobile||'')))rowErrors.push('Invalid mobile');if(duplicateMobile.has(i))rowErrors.push('Duplicate mobile in file');if(rowErrors.length)errors.push({row:i+1,errors:rowErrors,row:r});else valid.push(r)});return {valid,errors,duplicateMobile}}
export function saveMappingTemplate(name,mapping){const key='crm2_import_mapping_templates';const all=JSON.parse(localStorage.getItem(key)||'{}');all[String(name).trim()]=mapping;localStorage.setItem(key,JSON.stringify(all));return all}
export function loadMappingTemplates(){return JSON.parse(localStorage.getItem('crm2_import_mapping_templates')||'{}')}
export function downloadErrorReport(errors,filename='crm2-import-errors.csv'){const escCsv=v=>`"${String(v??'').replace(/"/g,'""')}"`;const header=['row','errors',...Object.keys(errors[0]?.row||{})];const lines=[header.map(escCsv).join(',')].concat(errors.map(e=>[e.row,e.errors.join('; '),...header.slice(2).map(k=>e.row[k])].map(escCsv).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function enhanceImportPage(){const root=document.querySelector('#main');if(!root||!root.textContent.includes('Import Leads')||root.querySelector('#crm2ImportQuality'))return;const panel=document.createElement('section');panel.id='crm2ImportQuality';panel.className='panel';panel.innerHTML='<h3>Import Quality Tools</h3><p class="muted">Validate required fields, detect same-file duplicate mobiles, save reusable column mapping templates, and export row-level errors.</p><div class="toolbar"><input id="mappingName" placeholder="Mapping template name"><button class="btn alt" id="saveMapping">Save mapping template</button><button class="btn alt" id="downloadImportErrors">Download Error Report</button></div>';root.appendChild(panel);document.querySelector('#saveMapping').onclick=()=>{const name=document.querySelector('#mappingName').value.trim();if(name)saveMappingTemplate(name,{});};document.querySelector('#downloadImportErrors').onclick=()=>downloadErrorReport([])}
new MutationObserver(enhanceImportPage).observe(document.body,{childList:true,subtree:true});
