import {sb,normalizeMobile,currentProfile} from '../data.js';
const REQUIRED=['customer_name','mobile'];
export function normalizeHeaders(headers){return headers.map(x=>String(x??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''))}
export function detectDuplicates(rows){const seenMobiles=new Set(),duplicateMobile=new Set();rows.forEach((r,i)=>{const m=normalizeMobile(r.mobile||'');if(m&&seenMobiles.has(m))duplicateMobile.add(i);if(m)seenMobiles.add(m)});return {seenMobiles,duplicateMobile}}
export function validateImportRows(rows){const errors=[],valid=[];const {duplicateMobile}=detectDuplicates(rows);rows.forEach((r,i)=>{const rowErrors=[];if(!String(r.customer_name||'').trim())rowErrors.push('Missing customer_name');if(!/^\d{10}$/.test(normalizeMobile(r.mobile||'')))rowErrors.push('Invalid mobile');if(duplicateMobile.has(i))rowErrors.push('Duplicate mobile in file');if(rowErrors.length)errors.push({row:i+1,errors:rowErrors,row:r});else valid.push(r)});return {valid,errors,duplicateMobile}}
export function saveMappingTemplate(name,mapping){const key='crm2_import_mapping_templates';const all=JSON.parse(localStorage.getItem(key)||'{}');all[String(name).trim()]=mapping;localStorage.setItem(key,JSON.stringify(all));return all}
export function loadMappingTemplates(){return JSON.parse(localStorage.getItem('crm2_import_mapping_templates')||'{}')}
export function downloadErrorReport(errors,filename='crm2-import-errors.csv'){const escCsv=v=>`"${String(v??'').replace(/"/g,'""')}"`;const header=['row','errors',...Object.keys(errors[0]?.row||{})];const lines=[header.map(escCsv).join(',')].concat(errors.map(e=>[e.row,e.errors.join('; '),...header.slice(2).map(k=>e.row[k])].map(escCsv).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function refreshActualImportErrors(){try{const me=await currentProfile();if(!me)return;const {data:imp}=await sb.from('imports').select('id').eq('created_by',me.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!imp){window.crm2ImportErrors=[];return}const {data:rows}=await sb.from('import_rows').select('row_no,raw_data,error_message,status').eq('import_id',imp.id).neq('status','validated').order('row_no');window.crm2ImportErrors=(rows||[]).map(x=>({row:x.row_no,errors:[x.error_message||x.status||'Invalid row'],row:x.raw_data||{}}))}catch(e){console.warn('Import quality refresh failed',e)}}
function captureMapping(){const map={};document.querySelectorAll('#mapForm [data-map]').forEach(s=>{map[s.dataset.map]=s.value===''?null:Number(s.value)});window.crm2ImportMapping=map;return map}
export function enhanceImportPage(){const root=document.querySelector('#main');if(!root||!root.textContent.includes('Import Leads')||root.querySelector('#crm2ImportQuality'))return;window.crm2ImportErrors=window.crm2ImportErrors||[];window.crm2ImportMapping=window.crm2ImportMapping||{};const panel=document.createElement('section');panel.id='crm2ImportQuality';panel.className='panel';panel.innerHTML='<h3>Import Quality Tools</h3><p class="muted">Reusable mappings and real staged-row errors are available here. Error export reads the current CRM2 import staging records.</p><div class="toolbar"><input id="mappingName" placeholder="Mapping template name"><button class="btn alt" id="saveMapping">Save mapping template</button><button class="btn alt" id="loadMapping">Load mapping template</button><button class="btn alt" id="downloadImportErrors">Download Error Report</button></div><p id="importQualityMsg" class="msg"></p>';root.appendChild(panel);document.querySelector('#saveMapping').onclick=()=>{const name=document.querySelector('#mappingName').value.trim();const mapping=captureMapping();if(name){saveMappingTemplate(name,mapping);document.querySelector('#importQualityMsg').textContent='Mapping template saved.'}else document.querySelector('#importQualityMsg').textContent='Enter a template name.'};document.querySelector('#loadMapping').onclick=()=>{const all=loadMappingTemplates(),names=Object.keys(all);if(!names.length){document.querySelector('#importQualityMsg').textContent='No saved mapping templates.';return}const name=prompt('Template name',names[0]);const map=all[name];if(!map){document.querySelector('#importQualityMsg').textContent='Template not found.';return}window.crm2ImportMapping=map;document.querySelectorAll('#mapForm [data-map]').forEach(s=>{if(Object.prototype.hasOwnProperty.call(map,s.dataset.map))s.value=map[s.dataset.map]??''});document.querySelector('#importQualityMsg').textContent='Mapping template loaded.'};document.querySelector('#downloadImportErrors').onclick=async()=>{await refreshActualImportErrors();if(!window.crm2ImportErrors.length){document.querySelector('#importQualityMsg').textContent='No staged import errors found.';return}downloadErrorReport(window.crm2ImportErrors)};const mapForm=document.querySelector('#mapForm');if(mapForm&&!mapForm.dataset.qualityHook){mapForm.dataset.qualityHook='1';mapForm.addEventListener('submit',captureMapping,true)}const commit=document.querySelector('#commitImport');if(commit&&!commit.dataset.qualityHook){commit.dataset.qualityHook='1';commit.addEventListener('click',()=>setTimeout(refreshActualImportErrors,300),true)}refreshActualImportErrors()}
new MutationObserver(enhanceImportPage).observe(document.body,{childList:true,subtree:true});
