import {sb,esc,fmtDate,money} from '../data.js';
import {changeShipmentStatus,createNdrCase,createRtoCase,recordPayment} from './workflows.js';
import {recordCodRemittance,recordSettlement,recordRefund,recordInventoryMovement} from './finance.js';

const $=id=>document.getElementById(id),main=()=>document.querySelector('#main');
const err=e=>e?.message||'Operation failed.';
const modal=(title,body)=>{document.querySelector('#crm2OpsModal')?.remove();const d=document.createElement('div');d.id='crm2OpsModal';d.innerHTML=`<div class="panel" style="position:fixed;inset:8%;z-index:9999;overflow:auto;box-shadow:0 8px 40px rgba(0,0,0,.25)"><div class="title"><h2>${esc(title)}</h2><button class="btn alt" id="opsClose">Close</button></div>${body}</div>`;document.body.appendChild(d);$('opsClose').onclick=()=>d.remove();return d};
const field=(id,label,value='',type='text')=>`<div class="field"><label>${esc(label)}</label><input id="${id}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''}></div>`;

async function shipmentActions(id){
  const {data:s,error}=await sb.from('shipments').select('id,order_id,courier,tracking_no,status').eq('id',id).single();
  if(error)throw error;
  const d=modal('Shipment Operations',`<p><b>Order:</b> ${esc(s.order_id)} · <b>Tracking:</b> ${esc(s.tracking_no||'—')}</p><form id="shipOps" class="grid2"><div class="field"><label>Action</label><select id="shipAction"><option value="status">Update Status</option><option value="ndr">Create NDR Case</option><option value="rto">Create RTO Case</option></select></div><div class="field"><label>Status</label><select id="shipStatus"><option>in_transit</option><option>out_for_delivery</option><option>delivered</option><option>dispatched</option><option>ndr</option><option>rto</option></select></div>${field('reason','Reason')} ${field('nextAction','Next Action At','', 'datetime-local')}<div class="field full"><label>Remarks</label><textarea id="shipRemarks"></textarea></div><button class="btn">Save Operation</button><div id="opsMsg" class="msg"></div></form>`);
  $('shipOps').onsubmit=async e=>{e.preventDefault();try{const a=$('shipAction').value,reason=$('reason').value.trim(),remarks=$('shipRemarks').value.trim();if(a==='status')await changeShipmentStatus(id,$('shipStatus').value,remarks);else if(a==='ndr')await createNdrCase({shipmentId:id,reason,remarks,nextActionAt:$('nextAction').value?new Date($('nextAction').value).toISOString():null});else await createRtoCase({shipmentId:id,reason,remarks});d.remove();await refreshDeliveryOps();}catch(x){$('opsMsg').textContent=err(x)}};
}

async function refreshDeliveryOps(){const m=main();if(!m)return;const {data}=await sb.from('shipments').select('id,order_id,courier,tracking_no,status,expected_delivery,updated_at').order('updated_at',{ascending:false}).limit(200);const rows=(data||[]).map(x=>`<tr><td>${esc(x.order_id)}</td><td>${esc(x.courier||'—')}</td><td>${esc(x.tracking_no||'—')}</td><td>${esc(x.status)}</td><td>${fmtDate(x.expected_delivery)}</td><td>${fmtDate(x.updated_at)}</td><td><button class="btn alt" data-ship="${x.id}">Operations</button></td></tr>`).join('');m.innerHTML=`<div class="title"><h2>Delivery / NDR / RTO</h2></div><section class="panel">${rows?`<div class="tablewrap"><table><thead><tr><th>Order</th><th>Courier</th><th>Tracking</th><th>Status</th><th>Expected</th><th>Updated</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<p class="muted">No shipments.</p>'}</section><section class="panel"><h3>NDR Queue</h3>${await queueTable('ndr_cases','shipment_id,reason,attempt_no,next_action_at,status,created_at')}</section><section class="panel"><h3>RTO Queue</h3>${await queueTable('rto_cases','shipment_id,reason,inspection_status,restocked,status,created_at')}</section>`;m.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>shipmentActions(b.dataset.ship));}
async function queueTable(tableName,cols){const {data,error}=await sb.from(tableName).select(cols).order('created_at',{ascending:false}).limit(100);if(error)return `<p class="error">${esc(error.message)}</p>`;return `<div class="tablewrap"><table><thead><tr>${cols.split(',').map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${(data||[]).map(r=>`<tr>${cols.split(',').map(x=>`<td>${esc(r[x]??'—')}</td>`).join('')}</tr>`).join('')||'<tr><td class="muted">No records.</td></tr>'}</tbody></table></div>`}

async function financeActions(kind){const specs={payment:['Record Payment',`<form id="finForm" class="grid2">${field('orderId','Order ID')}${field('amount','Amount','','number')}${field('mode','Type','COD')}${field('ref','Reference')}<button class="btn">Save</button><div id="finMsg" class="msg"></div></form>`,async()=>recordPayment({orderId:$('orderId').value.trim(),amount:$('amount').value,mode:$('mode').value.trim(),reference:$('ref').value.trim()})],remittance:['COD Remittance',`<form id="finForm" class="grid2">${field('shipmentId','Shipment ID')}${field('amount','Amount','','number')}${field('courier','Courier')}${field('ref','Reference')}<button class="btn">Save</button><div id="finMsg" class="msg"></div></form>`,async()=>recordCodRemittance({shipmentId:$('shipmentId').value.trim(),amount:$('amount').value,courier:$('courier').value.trim(),reference:$('ref').value.trim()})],settlement:['Dealer Settlement',`<form id="finForm" class="grid2">${field('partyType','Party Type','dealer')}${field('partyId','Party ID')}${field('amount','Amount','','number')}${field('ref','Reference')}<button class="btn">Save</button><div id="finMsg" class="msg"></div></form>`,async()=>recordSettlement({partyType:$('partyType').value.trim(),partyId:$('partyId').value.trim(),amount:$('amount').value,reference:$('ref').value.trim()})],refund:['Refund',`<form id="finForm" class="grid2">${field('orderId','Order ID')}${field('amount','Amount','','number')}${field('ref','Reference')}<button class="btn">Save</button><div id="finMsg" class="msg"></div></form>`,async()=>recordRefund({orderId:$('orderId').value.trim(),amount:$('amount').value,reference:$('ref').value.trim()})]};const [title,body,save]=specs[kind];const d=modal(title,body);$('finForm').onsubmit=async e=>{e.preventDefault();try{await save();d.remove();accountsOps()}catch(x){$('finMsg').textContent=err(x)}}}
async function accountsOps(){const m=main();if(!m)return;const [p,c,s,r]=await Promise.all([sb.from('payments').select('order_id,amount,type,status,reference,created_at').order('created_at',{ascending:false}).limit(100),sb.from('cod_remittances').select('shipment_id,courier,amount,status,reference,remitted_at').order('remitted_at',{ascending:false}).limit(100),sb.from('settlements').select('party_type,party_id,amount,status,reference,created_at').order('created_at',{ascending:false}).limit(100),sb.from('refunds').select('*').order('created_at',{ascending:false}).limit(100)]);m.innerHTML=`<div class="title"><h2>Accounts / Finance</h2></div><section class="panel"><p><button class="btn" data-fin="payment">Payment</button> <button class="btn alt" data-fin="remittance">COD Remittance</button> <button class="btn alt" data-fin="settlement">Dealer Settlement</button> <button class="btn alt" data-fin="refund">Refund</button></p><h3>Payments</h3>${simpleRows(p.data,p.error,['order_id','amount','type','status','reference','created_at'])}<h3>COD Remittances</h3>${simpleRows(c.data,c.error,['shipment_id','courier','amount','status','reference','remitted_at'])}<h3>Settlements</h3>${simpleRows(s.data,s.error,['party_type','party_id','amount','status','reference','created_at'])}<h3>Refunds</h3>${simpleRows(r.data,r.error,Object.keys((r.data||[])[0]||{}).slice(0,7))}</section>`;m.querySelectorAll('[data-fin]').forEach(b=>b.onclick=()=>financeActions(b.dataset.fin));}
const simpleRows=(data,error,cols)=>error?`<p class="error">${esc(error.message)}</p>`:`<div class="tablewrap"><table><thead><tr>${cols.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${(data||[]).map(r=>`<tr>${cols.map(x=>`<td>${esc(r[x]??'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${Math.max(cols.length,1)}" class="muted">No records.</td></tr>`}</tbody></table></div>`;

async function inventoryOps(){const m=main();if(!m)return;const [i,mv,w]=await Promise.all([sb.from('inventory').select('id,sku,warehouse_id,on_hand,reserved,damaged,updated_at').order('sku').limit(200),sb.from('inventory_movements').select('sku,warehouse_id,movement_type,quantity,reference_type,reference_id,reason,created_at').order('created_at',{ascending:false}).limit(100),sb.from('warehouses').select('id,name,code').order('name')]);m.innerHTML=`<div class="title"><h2>Inventory / Warehouse</h2><button class="btn" id="movement">Record Movement</button></div><section class="panel"><h3>Stock</h3>${simpleRows(i.data,i.error,['sku','warehouse_id','on_hand','reserved','damaged','updated_at'])}</section><section class="panel"><h3>Movement History</h3>${simpleRows(mv.data,mv.error,['sku','warehouse_id','movement_type','quantity','reference_type','reference_id','reason','created_at'])}</section><section class="panel"><h3>Warehouses</h3>${simpleRows(w.data,w.error,['code','name','id'])}</section>`;$('movement').onclick=()=>movementForm()}
async function movementForm(){const d=modal('Inventory Movement',`<form id="mvForm" class="grid2">${field('sku','SKU')}${field('warehouseId','Warehouse ID')}${field('movementType','Movement Type','inward')}${field('quantity','Quantity','','number')}${field('reason','Reason')}${field('referenceType','Reference Type')}${field('referenceId','Reference ID')}<button class="btn">Save Movement</button><div id="mvMsg" class="msg"></div></form>`);$('mvForm').onsubmit=async e=>{e.preventDefault();try{await recordInventoryMovement({sku:$('sku').value.trim(),warehouseId:$('warehouseId').value.trim(),movementType:$('movementType').value.trim(),quantity:$('quantity').value,reason:$('reason').value.trim(),referenceType:$('referenceType').value.trim(),referenceId:$('referenceId').value.trim()});d.remove();inventoryOps()}catch(x){$('mvMsg').textContent=err(x)}}}

function watch(){document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b&&b.dataset.page==='delivery')setTimeout(refreshDeliveryOps,0);if(b&&b.dataset.page==='accounts')setTimeout(accountsOps,0);if(b&&b.dataset.page==='inventory')setTimeout(inventoryOps,0);const ship=e.target.closest('[data-ship]');if(ship&&main()?.querySelector('h2')?.textContent.includes('Delivery')){e.preventDefault();e.stopImmediatePropagation();shipmentActions(ship.dataset.ship)}},true);}
watch();
