import {sb,esc,money,currentProfile} from '../data.js';
const managers=['super_admin','admin','manager','assistant_manager','team_leader'];
const $=id=>document.getElementById(id);
export async function renderTargets(m){
 const me=await currentProfile();if(!managers.includes(me?.role)){m.innerHTML='<section class="panel error">Access denied.</section>';return}
 const [agents,targets,orders]=await Promise.all([sb.from('crm2_user_profiles').select('id,full_name').eq('active',true).in('role',['agent','team_leader']).order('full_name'),sb.from('agent_targets').select('*').order('period_start',{ascending:false}).limit(200),sb.from('orders').select('agent_id,total,created_at').not('agent_id','is',null).limit(5000)]);
 const people=agents.data||[],list=targets.data||[],sales=orders.data||[];
 const rows=list.map(t=>{const actual=sales.filter(o=>o.agent_id===t.agent_id&&String(o.created_at).slice(0,10)>=t.period_start&&String(o.created_at).slice(0,10)<=t.period_end);const revenue=actual.reduce((n,o)=>n+Number(o.total||0),0);return '<tr><td>'+esc(people.find(a=>a.id===t.agent_id)?.full_name||t.agent_id)+'</td><td>'+esc(t.period_start)+' – '+esc(t.period_end)+'</td><td>'+t.target_orders+'</td><td>'+actual.length+'</td><td>'+money(t.target_revenue)+'</td><td>'+money(revenue)+'</td><td><button class="btn alt" data-target-edit="'+t.id+'">Edit</button></td></tr>'}).join('');
 m.innerHTML='<div class="title"><h2>Agent Targets</h2><button class="btn" id="newTarget">Set Target</button></div><section class="panel"><h3>Target vs Actual</h3><div class="tablewrap"><table><thead><tr><th>Agent</th><th>Period</th><th>Order Target</th><th>Actual Orders</th><th>Revenue Target</th><th>Actual Revenue</th><th>Action</th></tr></thead><tbody>'+ (rows||'<tr><td colspan="7" class="muted">No targets.</td></tr>')+'</tbody></table></div></section>';
 const form=(existing=null)=>{m.innerHTML='<section class="panel"><h2>'+(existing?'Edit':'Set')+' Agent Target</h2><form id="targetForm" class="grid2"><div class="field"><label>Agent</label><select id="targetAgent">'+people.map(p=>'<option value="'+p.id+'">'+esc(p.full_name||p.id)+'</option>').join('')+'</select></div><div class="field"><label>Start</label><input id="targetStart" type="date" required></div><div class="field"><label>End</label><input id="targetEnd" type="date" required></div><div class="field"><label>Order target</label><input id="targetOrders" type="number" min="0" value="0"></div><div class="field"><label>Revenue target</label><input id="targetRevenue" type="number" min="0" value="0"></div><button class="btn">Save</button><button type="button" class="btn alt" id="targetCancel">Cancel</button><div id="targetMsg" class="msg"></div></form></section>';if(existing){$('targetAgent').value=existing.agent_id;$('targetStart').value=existing.period_start;$('targetEnd').value=existing.period_end;$('targetOrders').value=existing.target_orders??0;$('targetRevenue').value=existing.target_revenue??0}$('targetCancel').onclick=()=>renderTargets(m);$('targetForm').onsubmit=async e=>{e.preventDefault();const record={agent_id:$('targetAgent').value,period_start:$('targetStart').value,period_end:$('targetEnd').value,target_orders:Number($('targetOrders').value)||0,target_revenue:Number($('targetRevenue').value)||0};if(record.period_end<record.period_start){$('targetMsg').textContent='End date must not precede start date.';return}const q=existing?sb.from('agent_targets').update(record).eq('id',existing.id):sb.from('agent_targets').insert(record);const {error}=await q;if(error){$('targetMsg').textContent=error.message;return}renderTargets(m)}};
 $('newTarget').onclick=()=>form();m.querySelectorAll('[data-target-edit]').forEach(b=>b.onclick=()=>form(list.find(t=>t.id===b.dataset.targetEdit)));
}
window.crm2Targets=renderTargets;