import {sb,esc,fmtDate,updateVerification,currentProfile} from '../data.js';
const main=()=>document.querySelector('#main');
const table=(h,r)=>`<div class="tablewrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.length?r.join(''):`<tr><td colspan="${h.length}" class="muted">No records found.</td></tr>`}</tbody></table></div>`;
const msg=e=>e?.message||'Operation failed.';
async function followupEnhanced(){const m=main();if(!m)return;const {data,error}=await sb.from('followups').select('id,lead_id,customer_id,order_id,assigned_to,due_at,priority,reason,status,reminder,completed_at').order('due_at').limit(500);const now=Date.now(),rows=data||[],pending=rows.filter(x=>x.status==='pending'),overdue=pending.filter(x=>new Date(x.due_at).getTime()<now),completed=rows.filter(x=>x.status==='completed'),missed=rows.filter(x=>x.status==='missed'),upcoming=pending.filter(x=>new Date(x.due_at).getTime()>=now);m.innerHTML=`<div class="title"><h2>Follow-ups</h2></div><div class="cards"><div class="stat"><span>Due / Today</span><b>${pending.length-overdue.length}</b></div><div class="stat"><span>Overdue</span><b>${overdue.length}</b></div><div class="stat"><span>Upcoming</span><b>${upcoming.length}</b></div><div class="stat"><span>Completed</span><b>${completed.length}</b></div><div class="stat"><span>Missed</span><b>${missed.length}</b></div></div><section class="panel">${error?`<p class="error">${esc(error.message)}</p>`:table(['Due','Priority','Reason','Status','Linked Record','Action'],rows.map(x=>`<tr><td>${fmtDate(x.due_at)}</td><td>${esc(x.priority)}</td><td>${esc(x.reason)}</td><td>${esc(x.status)}${x.status==='pending'&&new Date(x.due_at)<new Date()?' · OVERDUE':''}</td><td>${esc(x.lead_id||x.order_id||x.customer_id||'—')}</td><td>${x.status==='pending'?`<button class="btn alt" data-fu-complete="${x.id}">Complete</button> <button class="btn alt" data-fu-reschedule="${x.id}">Reschedule</button>${new Date(x.due_at)<new Date()?` <button class="btn alt" data-fu-missed="${x.id}">Mark Missed</button>`:''}`:'—'}</td></tr>`))}</section>`;m.querySelectorAll('[data-fu-complete]').forEach(b=>b.onclick=async()=>{const {error:e}=await sb.from('followups').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',b.dataset.fuComplete);if(e)alert(msg(e));else followupEnhanced()});m.querySelectorAll('[data-fu-missed]').forEach(b=>b.onclick=async()=>{const {error:e}=await sb.from('followups').update({status:'missed'}).eq('id',b.dataset.fuMissed);if(e)alert(msg(e));else followupEnhanced()});m.querySelectorAll('[data-fu-reschedule]').forEach(b=>b.onclick=async()=>{const value=prompt('New due date/time (YYYY-MM-DDTHH:MM)');if(!value)return;const d=new Date(value);if(Number.isNaN(d.getTime()))return alert('Invalid date/time.');const {error:e}=await sb.from('followups').update({due_at:d.toISOString(),status:'pending',completed_at:null}).eq('id',b.dataset.fuReschedule);if(e)alert(msg(e));else followupEnhanced()})}
async function verificationEnhanced(){const m=main(),p=await currentProfile();if(!p)return;const {data,error}=await sb.from('order_verifications').select('id,order_id,verifier_id,status,remarks,verified_at,created_at').order('created_at',{ascending:false}).limit(500);m.innerHTML=`<div class="title"><h2>Verification Queue & History</h2></div><section class="panel"><p class="muted">Every decision remains visible as a verification history record. Authorized verification/admin users can update decisions.</p>${error?`<p class="error">${esc(error.message)}</p>`:table(['Order','Status','Remarks','Verifier','Created','Verified','Action'],(data||[]).map(x=>`<tr><td>${esc(x.order_id)}</td><td><span class="pill">${esc(x.status)}</span></td><td>${esc(x.remarks||'')}</td><td>${esc(x.verifier_id||'—')}</td><td>${fmtDate(x.created_at)}</td><td>${fmtDate(x.verified_at)}</td><td>${['verification','super_admin','admin','manager','assistant_manager'].includes(p.role)?`<button class="btn alt" data-v="${x.id}">Decision</button>`:'—'}</td></tr>`))}</section>`;m.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>decision(b.dataset.v))}
function decision(id){const d=document.createElement('div');d.id='crm2VerifyModal';d.innerHTML=`<div class="panel" style="position:fixed;inset:15%;z-index:9999;overflow:auto"><div class="title"><h2>Verification Decision</h2><button class="btn alt" id="vClose">Close</button></div><form id="vForm"><div class="field"><label>Status</label><select id="vStatus"><option>Verified</option><option>Rejected</option><option>Callback Required</option><option>Wrong Number</option><option>Duplicate</option><option>Suspected Fraud</option></select></div><div class="field"><label>Remarks</label><textarea id="vRemarks" required></textarea></div><button class="btn">Save Decision</button><p id="vMsg" class="msg"></p></form></div>`;document.body.appendChild(d);document.querySelector('#vClose').onclick=()=>d.remove();document.querySelector('#vForm').onsubmit=async e=>{e.preventDefault();try{await updateVerification(id,$('#vStatus').value,$('#vRemarks').value);d.remove();verificationEnhanced()}catch(x){document.querySelector('#vMsg').textContent=msg(x)}}}
const $=id=>document.getElementById(id);
function watch(){document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;if(b.dataset.page==='followups')setTimeout(followupEnhanced,0);if(b.dataset.page==='verification')setTimeout(verificationEnhanced,0)},true)}
watch();
export {followupEnhanced,verificationEnhanced};
