import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.45.4/+esm';
const C=window.CRM2_CONFIG||{};
export const sb=createClient(C.supabaseUrl,C.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
export const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
export const fmtDate=v=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'short',timeStyle:'short'}):'—';
export const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})`;
export function normalizeMobile(v){return String(v??'').replace(/\D/g,'').slice(-10)}
export function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()!==''))rows.push(row);row=[];cell='';continue}cell+=c}if(cell!==''||row.length){row.push(cell);rows.push(row)}return rows}
export async function currentProfile(){const {data:{user}}=await sb.auth.getUser();if(!user){document.documentElement.removeAttribute('data-crm2-role');return null}const {data,error}=await sb.from('crm2_user_profiles').select('id,full_name,role,team_id,active').eq('id',user.id).maybeSingle();if(error||!data||!data.active){document.documentElement.removeAttribute('data-crm2-role');return null}document.documentElement.dataset.crm2Role=data.role;return {...user,...data}}
export async function getSources(){return sb.from('lead_sources').select('id,name').eq('active',true).order('name')}
export async function getProducts(){return sb.from('products').select('id,sku,name,cost,mrp,selling_price,active').eq('active',true).order('name')}
export async function searchLeads(term=''){let q=sb.from('leads').select('id,lead_code,customer_id,customer_name,mobile,product_name,source,status,priority,assigned_to,next_followup,created_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(100);if(term){const t=term.replace(/[%(),]/g,'');q=q.or(`mobile.ilike.%${t}%,customer_name.ilike.%${t}%,lead_code.ilike.%${t}%`)}return q}
export async function createLead(input){const mobile=normalizeMobile(input.mobile);if(mobile.length!==10)throw new Error('Valid 10-digit mobile number is required.');const {data:dups}=await sb.from('leads').select('id').eq('mobile',mobile).is('deleted_at',null).limit(1);if(dups?.length)throw new Error('Duplicate mobile already exists in an active lead.');return sb.from('leads').insert({...input,mobile}).select().single()}
export async function logCall({lead,agentId,outcome,dispositionId,notes,source='manual_mobile',direction='outbound',duration=0}){const {data,error}=await sb.from('lead_calls').insert({lead_id:lead.id,customer_id:lead.customer_id,agent_id:agentId,call_source:source,direction,outcome,disposition_id:dispositionId||null,notes,duration_seconds:Number(duration)||0,started_at:new Date().toISOString(),ended_at:new Date().toISOString()}).select().single();if(error)throw error;const status=outcome==='Connected'?'working':'callback';await sb.from('leads').update({status,disposition_id:dispositionId||null}).eq('id',lead.id);return data}
export async function createFollowup(input){return sb.from('followups').insert(input).select().single()}
export async function completeFollowup(id){return sb.from('followups').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id)}
export async function updateOrderStatus(id,status,remarks=''){const {error}=await sb.from('orders').update({status}).eq('id',id);if(error)throw error;await sb.from('order_status_history').insert({order_id:id,status,remarks});return true}
export async function updateVerification(id,status,remarks){const {error}=await sb.from('order_verifications').update({status,remarks,verified_at:['Verified','Rejected'].includes(status)?new Date().toISOString():null,verifier_id:(await sb.auth.getUser()).data.user?.id}).eq('id',id);if(error)throw error;return true}
export async function softDeleteLead(id,reason){return sb.from('leads').update({deleted_at:new Date().toISOString(),deleted_by:(await sb.auth.getUser()).data.user?.id,delete_reason:reason}).eq('id',id)}
