const escHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const navClick=(label)=>{const b=[...document.querySelectorAll('.side button')].find(x=>x.textContent.trim()===label);if(b)b.click()};
const textOf=(el)=>el?.textContent?.trim()||'';
const valueOf=(label)=>{const stat=[...document.querySelectorAll('.stat')].find(x=>textOf(x.querySelector('span'))===label);return Number(textOf(stat?.querySelector('b')).replace(/[^0-9.-]/g,''))||0};
const kpi=(label,value,meta='')=>`<article class="kpi-card"><span class="kpi-label">${escHtml(label)}</span><b class="kpi-value">${escHtml(value)}</b>${meta?`<div class="kpi-meta">${escHtml(meta)}</div>`:''}</article>`;
const barChart=(id,title,desc,items)=>`<article class="analytics-card" data-chart="${id}"><h3>${escHtml(title)}</h3><p>${escHtml(desc)}</p><div class="chart-bars">${items.map(([label,value,max])=>{const h=max?Math.max(4,Math.round(value/max*150)):4;return `<div class="chart-bar" title="${escHtml(label)}: ${value}"><b>${value}</b><i style="--bar-h:${h}px"></i><small>${escHtml(label)}</small></div>`}).join('')}</div></article>`;
const statusChart=(id,title,desc,items)=>`<article class="analytics-card" data-chart="${id}"><h3>${escHtml(title)}</h3><p>${escHtml(desc)}</p><div class="status-grid">${items.map(([label,value])=>`<div class="status-box"><b>${value}</b><span>${escHtml(label)}</span></div>`).join('')}</div></article>`;
function pageHeader(main,title,subtitle,actions=''){let old=main.querySelector('.title');if(!old)return;const h=old.querySelector('h2');if(!h)return;const date=old.querySelector('.muted');old.className='page-header';old.innerHTML=`<div><h2>${h.innerHTML}</h2>${subtitle?`<p class="page-subtitle">${escHtml(subtitle)}</p>`:''}</div><div class="page-actions">${actions}${date?`<span class="muted">${date.innerHTML}</span>`:''}</div>`;}
function enhanceGeneric(main){main.classList.add('erp-workspace');const title=textOf(main.querySelector('.title h2'));if(title==='Leads'){const toolbar=main.querySelector('.toolbar');if(toolbar)toolbar.classList.add('filter-bar');pageHeader(main,'Leads','Manage, assign and convert customer enquiries.');}else if(title==='Customer 360'){pageHeader(main,'Customers','View the complete customer journey and order history.');}else if(title==='Calling Workspace'){pageHeader(main,'Calling','Work through today’s customer queue and record every outcome.');}else if(title==='Management Dashboard'){return;}else if(main.querySelector('.title'))pageHeader(main,title,'Operate this module from one focused workspace.');}
function enhanceDashboard(main){if(main.dataset.modernized==='dashboard')return;const oldCards=main.querySelector('.cards');if(!oldCards)return;const labels=['Active Leads','Orders','Pending Follow-ups','Delivered','RTO','Role'];const vals=Object.fromEntries(labels.map(l=>[l,textOf([...oldCards.querySelectorAll('.stat')].find(s=>textOf(s.querySelector('span'))===l)?.querySelector('b'))]));const l=valueOf('Active Leads'),o=valueOf('Orders'),f=valueOf('Pending Follow-ups'),d=valueOf('Delivered'),r=valueOf('RTO');const max=Math.max(l,o,f,d,r,1);main.innerHTML=`<div class="page-header"><div><h2>Management Dashboard</h2><p class="page-subtitle">A clear real-time view of sales, operations and pending actions.</p></div><div class="page-actions"><span class="muted">${new Date().toLocaleDateString('en-IN')}</span></div></div><section class="kpi-grid">${kpi('Active Leads',vals['Active Leads'],'Live enquiries')}${kpi('Orders',vals.Orders,'Orders created')}${kpi('Pending Follow-ups',vals['Pending Follow-ups'],'Needs attention')}${kpi('Delivered',vals.Delivered,'Completed deliveries')}${kpi('RTO',vals.RTO,'Returned shipments')}${kpi('Role',vals.Role,'Current access')}</section><section class="panel"><div class="section-head"><div><h3>Business Funnel</h3><p class="muted">Current volume across the core teleshopping journey.</p></div></div><div class="business-funnel"><div class="funnel-step"><b>${l}</b><span>Leads</span></div><div class="funnel-arrow">→</div><div class="funnel-step"><b>${o}</b><span>Orders</span></div><div class="funnel-arrow">→</div><div class="funnel-step"><b>${d}</b><span>Delivered</span></div><div class="funnel-arrow">/</div><div class="funnel-step"><b>${r}</b><span>RTO</span></div></div></section><section class="analytics-grid">${barChart('sales-trend','Business activity','Actual current KPI counts; no synthetic history is shown.',[['Leads',l,max],['Orders',o,max],['Follow-ups',f,max],['Delivered',d,max],['RTO',r,max]])}${statusChart('order-status','Order & delivery health','Live operational totals from CRM2.',[['Orders',o],['Delivered',d],['RTO',r],['Follow-ups',f]])}${statusChart('agent-performance','Agent performance','Agent-level performance will populate as assigned leads and orders are recorded.',[] )}</section><section class="panel"><div class="section-head"><div><h3>Quick Actions</h3><p class="muted">Jump directly to the work you need to do.</p></div></div><div class="quick-actions"><button class="quick-action" data-modern-nav="Leads">View Leads</button><button class="quick-action" data-modern-nav="Calling">Open Calling</button><button class="quick-action" data-modern-nav="Orders">View Orders</button><button class="quick-action" data-modern-nav="Follow-ups">Check Follow-ups</button><button class="quick-action" data-modern-nav="Verification">Verify Orders</button></div></section>`;main.querySelectorAll('[data-modern-nav]').forEach(b=>b.onclick=()=>navClick(b.dataset.modernNav));main.dataset.modernized='dashboard';}
function run(){const main=document.querySelector('#main');if(!main)return;if(main.querySelector('.title h2')?.textContent.trim()==='Management Dashboard'){enhanceDashboard(main);return;}enhanceGeneric(main);}
const observer=new MutationObserver(()=>requestAnimationFrame(run));
function start(){run();const main=document.querySelector('#main');if(main)observer.observe(main,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
window.crm2ModernUI={run};
