/* Zero-dependency static smoke tests. Run with: node crm2/tests/smoke.js */
const fs=require('fs'),path=require('path');
const dir=path.resolve(__dirname,'..');
const repoRoot=path.resolve(__dirname,'../..');
const read=f=>fs.readFileSync(path.join(dir,f),'utf8');
const index=read('index.html'),app=read('app.js'),data=read('data.js'),workflow=read('modules/workflows.js'),finance=read('modules/finance.js'),ops=read('modules/operations-ui.js'),admin=read('modules/admin-ui.js'),management=read('modules/management-ui.js'),imports=read('modules/import-ui.js'),dealer=read('modules/dealer-ui.js'),targets=read('modules/targets-ui.js'),config=read('config.js');
function ok(name,cond){if(!cond)throw new Error('FAIL: '+name);console.log('PASS: '+name)}
ok('index loads current app module',index.includes('src="./app.js"'));
ok('index loads operational UI module',index.includes('src="./modules/operations-ui.js"'));
ok('index loads admin UI module',index.includes('src="./modules/admin-ui.js"'));
ok('index loads management UI module',index.includes('src="./modules/management-ui.js"'));
ok('index loads import quality module',index.includes('src="./modules/import-ui.js"'));
ok('index loads workflow UI module',index.includes('src="./modules/workflow-ui.js"'));
ok('index does not load duplicate Supabase client',!index.includes('supabase-js'));
ok('no legacy/fix JS',!index.includes('path-fix.js')&&!index.includes('routing-fix.js')&&!index.includes('lead-upload-fix.js'));
ok('manual mobile calling is first-class',app.includes('tel:')&&data.includes('manual_mobile'));
ok('working lead status is used',data.includes("'working'"));
ok('call logging stores disposition',data.includes('disposition_id'));
ok('CRM2 tables are wired',app.includes("from('leads')")&&app.includes("from('orders')")&&app.includes("from('customers')"));
ok('import workflow exists',app.includes('Validate & Stage')&&app.includes('Import Valid Leads')&&app.includes('import_rows'));
ok('customer 360 exists',app.includes('customer360'));
ok('operational workflow module exists',workflow.includes('createOrderFromLead')&&workflow.includes('changeShipmentStatus')&&workflow.includes('createNdrCase')&&workflow.includes('createRtoCase'));
ok('shipment event schema is mapped correctly',workflow.includes('event_status:status')&&workflow.includes('event_time:new Date().toISOString()'));
ok('NDR/RTO schema fields are mapped correctly',workflow.includes('attempt_no:1')&&workflow.includes('inspection_status:remarks')&&workflow.includes('restocked:false'));
ok('order item is created with fast order',workflow.includes("from('order_items')")&&workflow.includes('line_total:total'));
ok('finance RPC adapters exist',finance.includes('crm2_record_cod_remittance')&&finance.includes('crm2_record_settlement')&&finance.includes('crm2_record_refund')&&finance.includes('crm2_record_inventory_movement'));
ok('delivery UI exposes NDR/RTO actions',ops.includes('data-ship')&&ops.includes('value="ndr"')&&ops.includes('value="rto"')&&ops.includes('createNdrCase')&&ops.includes('createRtoCase'));
ok('accounts UI exposes finance workflows',ops.includes('recordCodRemittance')&&ops.includes('recordSettlement')&&ops.includes('recordRefund')&&ops.includes('recordPayment'));
ok('inventory UI exposes stock movement workflow',ops.includes('recordInventoryMovement')&&ops.includes('inventory_movements'));
ok('payments UI uses schema-correct type',app.includes("select('order_id,amount,type,status,reference,created_at')")&&app.includes('x.type'));
ok('admin module provides role-aware navigation',admin.includes('currentProfile')&&admin.includes('ROLES')&&admin.includes('Admin / Config'));
ok('admin module owns configuration entities',admin.includes('disposition_levels')&&admin.includes('campaigns')&&admin.includes('products')&&admin.includes('warehouses')&&admin.includes('couriers'));
ok('assignment workflow is exposed',admin.includes('lead_assignments')&&admin.includes('assigned_to')&&admin.includes('agent_id'));
ok('bulk assignment and lead filters exist',management.includes('Bulk Assign')&&management.includes('data-bulk-lead')&&management.includes('assignQ')&&management.includes('assignment_date'));
ok('MIS drilldown reporting exists',management.includes('MIS Drilldown')&&management.includes('agent_id')&&management.includes('campaign_id')&&management.includes('conversion'));
ok('management pages are mounted from navigation',admin.includes('mountManagement')&&admin.includes('data-admin="mis"')&&admin.includes('data-admin="assignments"'));
ok('import mapping templates and row error export exist',imports.includes('mapping template')&&imports.includes('Download Error Report')&&imports.includes('import_rows'));
ok('same-file duplicate detection exists',imports.includes('duplicateMobile')&&imports.includes('seenMobiles'));
ok('import quality panel is wired to real errors',imports.includes('window.crm2ImportErrors')&&imports.includes('downloadErrorReport(window.crm2ImportErrors'));
ok('mapping template saves actual mapping',imports.includes('window.crm2ImportMapping')&&imports.includes('saveMappingTemplate(name,window.crm2ImportMapping)'));
ok('role-aware core navigation hides restricted pages',admin.includes('RESTRICTED_PAGES')&&admin.includes('applyRoleNavigation'));
ok('fast order UI supports mobile customer matching',ops.includes('createOrderFromLead')&&ops.includes('Customer Mobile')&&ops.includes('normalizeMobile')&&ops.includes('fastOrderForm'));
ok('fast order uses product selector',ops.includes('getProducts')&&ops.includes('productId'));
ok('follow-up UI provides due/overdue/missed/reschedule workflow',index.includes('workflow-ui.js'));
ok('verification UI exposes history and decisions',index.includes('workflow-ui.js'));
ok('no service role secret',!config.includes('service_role')&&!app.includes('service_role')&&!data.includes('service_role')&&!workflow.includes('service_role')&&!finance.includes('service_role')&&!ops.includes('service_role')&&!admin.includes('service_role')&&!management.includes('service_role')&&!imports.includes('service_role'));
ok('no CRM1 navigation dependency',!app.includes('../crm/')&&!app.includes('../crm1/')&&!ops.includes('../crm/')&&!ops.includes('../crm1/')&&!admin.includes('../crm/')&&!admin.includes('../crm1/')&&!management.includes('../crm/')&&!management.includes('../crm1/')&&!imports.includes('../crm/')&&!imports.includes('../crm1/'));
ok('no Google Drive dependency',![app,data,workflow,finance,ops,admin,management,imports].some(x=>x.includes('Google Drive')));
for(const f of fs.readdirSync(dir,{recursive:true}))if(typeof f==='string'&&/^.+-(v\d+|final|fix)\.js$/i.test(f))throw new Error('Legacy/versioned CRM2 JS remains: '+f);
ok('NDR lifecycle actions are implemented',workflow.includes('reattemptNdrCase')&&workflow.includes('closeNdrCase')&&ops.includes('reattempt_ndr')&&ops.includes('close_ndr'));
ok('RTO inspection and restock are implemented',workflow.includes('inspectRtoCase')&&workflow.includes('restockRtoCase')&&ops.includes('inspect_rto')&&ops.includes('restock_rto')&&ops.includes('recordInventoryMovement'));
ok('dealer management has CRUD and performance controls',index.includes('dealer-ui.js')&&dealer.includes("from('dealers')")&&dealer.includes("from('orders')")&&dealer.includes("from('settlements')")&&dealer.includes('data-dealer-edit')&&dealer.includes('Dealer Performance'));
ok('dealer removal is safe and non-destructive',dealer.includes("status:'inactive'")&&dealer.includes('Mark it inactive instead'));
ok('inventory uses SKU and warehouse selectors with low-stock attention',ops.includes('inventoryProduct')&&ops.includes('inventoryWarehouse')&&ops.includes('Needs Attention')&&ops.includes('available'));
ok('import large-file guard is enforced before parsing',imports.includes('MAX_IMPORT_BYTES')&&imports.includes('file.size > MAX_IMPORT_BYTES')&&imports.includes('stopImmediatePropagation'));
ok('agent targets have management and actual-performance reporting',index.includes('targets-ui.js')&&targets.includes("from('agent_targets')")&&targets.includes("from('orders')")&&targets.includes('Target vs Actual'));
ok('agent targets support editing existing periods',targets.includes('data-target-edit')&&targets.includes(".update(record)")&&targets.includes('Edit'));
ok('import error export preserves numeric row and source row data',imports.includes("row:x.row_no")&&imports.includes('row_data:x.raw_data')&&imports.includes('rowData'));
ok('dealer and target changes are covered by database audit triggers',admin.includes("from('dealers')")&&targets.includes("from('agent_targets')")&&fs.existsSync(path.join(repoRoot,'supabase/migrations/20260909200000_crm2_audit_dealer_targets.sql')));
console.log('CRM2 static smoke suite passed');
