/* Zero-dependency static smoke tests. Run with: node crm2/tests/smoke.js */
const fs=require('fs'),path=require('path');
const dir=path.resolve(__dirname,'..');
const repoRoot=path.resolve(__dirname,'../..');
const read=f=>fs.readFileSync(path.join(dir,f),'utf8');
const index=read('index.html'),app=read('app.js'),data=read('data.js'),workflow=read('modules/workflows.js'),finance=read('modules/finance.js'),ops=read('modules/operations-ui.js'),admin=read('modules/admin-ui.js'),management=read('modules/management-ui.js'),imports=read('modules/import-ui.js'),dealer=read('modules/dealer-ui.js'),targets=read('modules/targets-ui.js'),config=read('config.js'),navRole=read('modules/nav-role-ui.js'),createOrder=read('modules/create-order-ui.js'),createOrderBridge=read('modules/create-order-bridge.js'),createOrderAddress=read('modules/create-order-address.js'),createOrderCalling=read('modules/create-order-calling.js');
function ok(name,cond){if(!cond)throw new Error('FAIL: '+name);console.log('PASS: '+name)}
ok('index loads current app module',/src="\.\/app\.js\?v=/.test(index));
ok('index loads operational UI module',/src="\.\/modules\/operations-ui\.js\?v=/.test(index));
ok('index loads admin UI module',/src="\.\/modules\/admin-ui\.js\?v=/.test(index));
ok('index loads management UI module',/src="\.\/modules\/management-ui\.js\?v=/.test(index));
ok('index loads import quality module',/src="\.\/modules\/import-ui\.js\?v=/.test(index));
ok('index loads workflow UI module',/src="\.\/modules\/workflow-ui\.js\?v=/.test(index));
ok('index loads independent role navigation module',/src="\.\/modules\/nav-role-ui\.js\?v=\d+-\d+/.test(index));
ok('index loads create order workspace module',/src="\.\/modules\/create-order-ui\.js\?v=\d+-\d+/.test(index));
ok('index loads create order calling lifecycle module',/src="\.\/modules\/create-order-calling\.js\?v=\d+-\d+/.test(index));
ok('role/navigation modules use a cache-bust version',/src="\.\/modules\/nav-role-ui\.js\?v=\d+-\d+/.test(index));
ok('role navigation renderer exposes management labels',navRole.includes('Lead Assignment')&&navRole.includes('MIS Drilldown'));
ok('index does not load duplicate Supabase client',!index.includes('supabase-js')&&data.match(/createClient\(/g)?.length===1);
ok('no legacy/fix JS',!index.includes('legacy')&&!index.includes('fix.js'));
ok('manual mobile calling is first-class',createOrder.includes('tel:'));
ok('working lead status is used',workflow.includes("status:'callback'")||workflow.includes('status = callback')||createOrderCalling.includes("status:'callback'"));
ok('call logging stores disposition',data.includes('disposition_id')||workflow.includes('disposition')||createOrder.includes('disposition'));
ok('CRM2 tables are wired',app.includes("from('leads')")&&app.includes("from('customers')"));
ok('import workflow exists',imports.includes('enhanceImportPage')&&imports.includes("from('import_rows')"));
ok('customer 360 exists',app.includes('customer360')||index.includes('customers'));
ok('operational workflow module exists',workflow.includes('crm2_create_order_workspace'));
ok('shipment event schema is mapped correctly',ops.includes('shipment_events')&&ops.includes('event_type'));
ok('NDR/RTO schema fields are mapped correctly',ops.includes('ndr_cases')&&ops.includes('rto_cases'));
ok('order item is created with fast order',workflow.includes('order_items'));
ok('finance RPC adapters exist',finance.includes('rpc('));
ok('delivery UI exposes NDR/RTO actions',ops.includes('Reattempt')&&ops.includes('RTO'));
ok('accounts UI exposes finance workflows',finance.includes('COD')||finance.includes('settlement'));
ok('inventory UI exposes stock movement workflow',ops.includes('inventory_movements'));
ok('payments UI uses schema-correct type',finance.includes('payment'));
ok('admin module provides role-aware navigation',admin.includes('role'));
ok('admin module owns configuration entities',admin.includes('products')&&admin.includes('campaigns'));
ok('assignment workflow is exposed',management.includes('assignment')||index.includes('Lead Assignment'));
ok('bulk assignment and lead filters exist',management.includes('bulk')||management.includes('assignment'));
ok('MIS drilldown reporting exists',management.includes('MIS Drilldown'));
ok('management pages are mounted from navigation',navRole.includes('MIS Drilldown')&&navRole.includes('Lead Assignment'));
ok('import mapping templates and row error export exist',imports.includes('mapping')&&imports.includes('error'));
ok('same-file duplicate detection exists',imports.includes('duplicate'));
ok('import quality panel is wired to real errors',imports.includes("from('import_rows')"));
ok('mapping template saves actual mapping',imports.includes('mapping_template')||imports.includes('mapping'));
ok('role-aware core navigation hides restricted pages',navRole.includes('agent')&&navRole.includes('Accounts'));
ok('fast order UI supports mobile customer matching',createOrder.includes('crm2OrderMobile'));
ok('fast order uses product selector',createOrder.includes('crm2OrderProduct'));
ok('follow-up UI provides due/overdue/missed/reschedule workflow',workflow.includes('followups'));
ok('verification UI exposes history and decisions',ops.includes('verification')||index.includes('Verification'));
ok('no service role secret',!index.includes('service_role')&&!config.includes('service_role'));
ok('no CRM1 navigation dependency',!index.includes('../crm1')&&!index.includes('/crm1/'));
ok('no Google Drive dependency',!index.toLowerCase().includes('drive.google.com'));
ok('NDR lifecycle actions are implemented',ops.includes('ndr_cases')&&ops.includes('reattempt'));
ok('RTO inspection and restock are implemented',ops.includes('rto_cases')&&ops.includes('restock'));
ok('dealer management has CRUD and performance controls',dealer.includes('dealers')&&dealer.includes('performance'));
ok('dealer removal is safe and non-destructive',!dealer.includes('delete(')||dealer.includes('soft'));
ok('inventory uses SKU and warehouse selectors with low-stock attention',ops.includes('inventoryProduct')&&ops.includes('inventoryWarehouse')&&ops.includes('Needs Attention')&&ops.includes('available'));
ok('import large-file guard is enforced before parsing',imports.includes('MAX_IMPORT_BYTES')&&imports.includes('file.size > MAX_IMPORT_BYTES')&&imports.includes('stopImmediatePropagation'));
ok('agent targets have management and actual-performance reporting',index.includes('targets-ui.js')&&targets.includes("from('agent_targets')")&&targets.includes("from('orders')")&&targets.includes('Target vs Actual'));
ok('agent targets support editing existing periods',targets.includes('data-target-edit')&&targets.includes('.update(record)')&&targets.includes('Edit'));
ok('import error export preserves numeric row and source row data',imports.includes("row:x.row_no")&&imports.includes('row_data:x.raw_data')&&imports.includes('rowData'));
ok('create order workspace has customer, call, address, pricing and summary flows',createOrder.includes('crm2OrderMobile')&&createOrder.includes('crm2CallMobile')&&createOrder.includes('crm2OrderPincode')&&createOrder.includes('crm2OrderProduct')&&createOrder.includes('crm2CreateOrder')&&createOrder.includes('crm2CustomerHistory'));
ok('create order uses atomic CRM2 RPC',createOrder.includes('crm2_create_order_workspace')&&createOrder.includes("sb.rpc('crm2_create_order_workspace'"));
ok('create order supports pincode auto-fill with fallback',createOrder.includes('api.postalpincode.in/pincode')&&createOrder.includes('Pincode lookup unavailable'));
ok('create order preserves attribution',createOrder.includes('campaign_id')&&createOrder.includes('source')&&createOrder.includes('priority'));
ok('create order supports manual and telephony call paths',createOrder.includes('tel:')&&createOrder.includes('crm2StartTelephonyCall'));
ok('Fast Order action is routed to the unified workspace',createOrderBridge.includes('Fast Order')&&createOrderBridge.includes('crm2OpenCreateOrder')&&createOrderBridge.includes('stopImmediatePropagation')&&createOrderBridge.includes("addEventListener('click'")&&createOrderBridge.includes(',true)'));
ok('create order call lifecycle has Start/End controls and timer',createOrderCalling.includes('crm2StartCall')&&createOrderCalling.includes('crm2EndCall')&&createOrderCalling.includes('crm2CallTimer')&&createOrderCalling.includes('duration_seconds'));
ok('call lifecycle stores start and end timestamps',createOrderCalling.includes('started_at')&&createOrderCalling.includes('ended_at'));
ok('callback scheduling stores due date/time and assignment',createOrderCalling.includes('due_at')&&createOrderCalling.includes('assigned_to')&&createOrderCalling.includes('Save Callback'));
ok('callback prevents duplicate active save',createOrderCalling.includes('callbackSaving'));
ok('active call survives refresh and is agent-scoped',createOrderCalling.includes('localStorage')&&createOrderCalling.includes('crm2ActiveCall')&&createOrderCalling.includes('agentId'));
ok('abandoned active calls expire with a persisted lifecycle',createOrderCalling.includes('Abandoned')&&createOrderCalling.includes('6*60*60*1000')&&createOrderCalling.includes('ended_at'));
ok('resilient pincode cascade keeps manual fallback',createOrderAddress.includes('Pincode lookup unavailable')&&createOrderAddress.includes('Select State'));
const auditName='20260909200000_crm2_audit_dealer_targets.sql';
const auditCandidates=[path.join(repoRoot,'supabase','migrations',auditName),path.join(process.cwd(),'supabase','migrations',auditName)];
const auditMigration=auditCandidates.find(p=>fs.existsSync(p));
const auditSql=auditMigration?fs.readFileSync(auditMigration,'utf8').toLowerCase():'';
ok('dealer and target changes are covered by database audit triggers',dealer.includes("from('dealers')")&&targets.includes("from('agent_targets')")&&!!auditMigration&&auditSql.includes('create trigger crm2_audit_dealer_change')&&auditSql.includes('on public.dealers')&&auditSql.includes('create trigger crm2_audit_agent_target_change')&&auditSql.includes('on public.agent_targets'));
const orderMigration=path.join(repoRoot,'supabase','migrations','20260910184343_crm2_create_order_workspace.sql');
const orderSql=fs.existsSync(orderMigration)?fs.readFileSync(orderMigration,'utf8').toLowerCase():'';
ok('create order migration defines the workspace RPC',orderSql.includes('create or replace function public.crm2_create_order_workspace'));